"""Add IEC104 station and point models

Revision ID: 6c6f9a11354b
Revises: e7f675deaec4
Create Date: 2025-06-03 08:30:00.449550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6f9a11354b'
down_revision = 'e7f675deaec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iec104_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('common_address', sa.Integer(), nullable=False),
    sa.Column('t0_timeout', sa.Integer(), nullable=True),
    sa.Column('t1_timeout', sa.Integer(), nullable=True),
    sa.Column('t2_timeout', sa.Integer(), nullable=True),
    sa.Column('t3_timeout', sa.Integer(), nullable=True),
    sa.Column('k_value', sa.Integer(), nullable=True),
    sa.Column('w_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('common_address')
    )
    op.create_table('iec104_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('io_address', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('point_type_str', sa.Enum('M_SP_NA_1', 'M_DP_NA_1', 'M_ME_NA_1', 'M_ME_NB_1', 'M_ME_NC_1', name='iec104pointtype'), nullable=False),
    sa.Column('report_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['iec104_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'io_address', name='_station_ioa_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iec104_points')
    op.drop_table('iec104_stations')
    # ### end Alembic commands ###
