"""Add connection_status to OpcServer

Revision ID: aae8e9df92c3
Revises: 
Create Date: 2025-05-30 19:16:16.474977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae8e9df92c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opc_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_status', sa.String(length=50), nullable=False,server_default='DISCONNECTED'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opc_servers', schema=None) as batch_op:
        batch_op.drop_column('connection_status')

    # ### end Alembic commands ###
