"""Add SubscriptionMapping with server_id and unique constraints

Revision ID: e7f675deaec4
Revises: aae8e9df92c3
Create Date: 2025-05-30 21:21:28.447157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f675deaec4'
down_revision = 'aae8e9df92c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('opc_node_db_id', sa.Integer(), nullable=False),
    sa.Column('ioa_mapping', sa.Integer(), nullable=False),
    sa.Column('sampling_interval_ms', sa.Integer(), nullable=False),
    sa.Column('publishing_interval_ms', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opc_node_db_id'], ['opc_nodes.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['opc_servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'ioa_mapping', name='uq_server_ioa_once_mapping'),
    sa.UniqueConstraint('server_id', 'opc_node_db_id', name='uq_server_node_once_mapping')
    )
    with op.batch_alter_table('subscription_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_mappings_ioa_mapping'), ['ioa_mapping'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_mappings_opc_node_db_id'), ['opc_node_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_mappings_server_id'), ['server_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_mappings_server_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_mappings_opc_node_db_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_mappings_ioa_mapping'))

    op.drop_table('subscription_mappings')
    # ### end Alembic commands ###
